builds:
  - binary: kube-manager
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: kube-manager
    homepage: "https://github.com/RinkiyaKeDad/kube-manager"
    repository:
      owner: RinkiyaKeDad
      name: homebrew-rinkiyakedad
    commit_author:
      name: RinkiyaKeDad
      email: arshsharma461@gmail.com

checksum:
  name_template: 'checksums.txt'